import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Generated by: flutterfire configure
/// Production values should be supplied through --dart-define or .env.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        return android;
    }
  }

  static FirebaseOptions get android => FirebaseOptions(
    apiKey: _requiredValue(
      'FIREBASE_ANDROID_API_KEY',
      const String.fromEnvironment('FIREBASE_ANDROID_API_KEY'),
    ),
    appId: _requiredValue(
      'FIREBASE_ANDROID_APP_ID',
      const String.fromEnvironment('FIREBASE_ANDROID_APP_ID'),
    ),
    messagingSenderId: _requiredValue(
      'FIREBASE_MESSAGING_SENDER_ID',
      const String.fromEnvironment('FIREBASE_MESSAGING_SENDER_ID'),
    ),
    projectId: _requiredValue(
      'FIREBASE_PROJECT_ID',
      const String.fromEnvironment('FIREBASE_PROJECT_ID'),
    ),
    storageBucket: _requiredValue(
      'FIREBASE_STORAGE_BUCKET',
      const String.fromEnvironment('FIREBASE_STORAGE_BUCKET'),
    ),
  );

  static FirebaseOptions get ios => FirebaseOptions(
    apiKey: _requiredValue(
      'FIREBASE_IOS_API_KEY',
      const String.fromEnvironment('FIREBASE_IOS_API_KEY'),
    ),
    appId: _requiredValue(
      'FIREBASE_IOS_APP_ID',
      const String.fromEnvironment('FIREBASE_IOS_APP_ID'),
    ),
    messagingSenderId: _requiredValue(
      'FIREBASE_MESSAGING_SENDER_ID',
      const String.fromEnvironment('FIREBASE_MESSAGING_SENDER_ID'),
    ),
    projectId: _requiredValue(
      'FIREBASE_PROJECT_ID',
      const String.fromEnvironment('FIREBASE_PROJECT_ID'),
    ),
    storageBucket: _requiredValue(
      'FIREBASE_STORAGE_BUCKET',
      const String.fromEnvironment('FIREBASE_STORAGE_BUCKET'),
    ),
    iosBundleId: const String.fromEnvironment(
      'IOS_BUNDLE_ID',
      defaultValue: 'com.drivio.app',
    ),
  );

  static FirebaseOptions get web => FirebaseOptions(
    apiKey: _requiredValue(
      'FIREBASE_WEB_API_KEY',
      const String.fromEnvironment('FIREBASE_WEB_API_KEY'),
    ),
    appId: _requiredValue(
      'FIREBASE_WEB_APP_ID',
      const String.fromEnvironment('FIREBASE_WEB_APP_ID'),
    ),
    messagingSenderId: _requiredValue(
      'FIREBASE_MESSAGING_SENDER_ID',
      const String.fromEnvironment('FIREBASE_MESSAGING_SENDER_ID'),
    ),
    projectId: _requiredValue(
      'FIREBASE_PROJECT_ID',
      const String.fromEnvironment('FIREBASE_PROJECT_ID'),
    ),
    storageBucket: _requiredValue(
      'FIREBASE_STORAGE_BUCKET',
      const String.fromEnvironment('FIREBASE_STORAGE_BUCKET'),
    ),
    authDomain: _requiredValue(
      'FIREBASE_AUTH_DOMAIN',
      const String.fromEnvironment('FIREBASE_AUTH_DOMAIN'),
    ),
  );

  static String _requiredValue(String key, String dartDefineValue) {
    final value = dartDefineValue.isNotEmpty
        ? dartDefineValue
        : dotenv.env[key];
    if (value == null || value.isEmpty) {
      throw StateError('Missing required Firebase config value: $key');
    }
    return value;
  }
}
